version: "3.9"

services:
  milvus-etcd-word:
    container_name: milvus-etcd-word
    image: quay.io/coreos/etcd:v3.5.18
    restart: on-failure
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: >
      etcd
      -advertise-client-urls=http://milvus-etcd-word:2379
      -listen-client-urls http://0.0.0.0:2379
      --data-dir /etcd
    volumes:
      - etcd_data_word:/etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-minio-word:
    container_name: milvus-minio-word
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: on-failure
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /minio_data --console-address ":9103"
    volumes:
      - minio_data_word:/minio_data
    ports:
      - "9102:9000"   # MinIO API
      - "9103:9103"   # MinIO Console
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-standalone-word:
    container_name: milvus-standalone-word
    image: milvusdb/milvus:v2.5.12
    command: [ "milvus", "run", "standalone" ]
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus-etcd-word:2379
      MINIO_ADDRESS: milvus-minio-word:9000
      MILVUS_USERNAME: ${MILVUS_USERNAME}
      MILVUS_PASSWORD: ${MILVUS_PASSWORD}
      common.security.authorizationEnabled: "true"
    volumes:
      - milvus_data_word:/var/lib/milvus
    ports:
      - "19630:19530"   # gRPC Milvus
      - "9191:9091"     # HTTP/metrics
    depends_on:
      - milvus-etcd-word
      - milvus-minio-word
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3

  milvus-attu-word:
    container_name: milvus-attu-word
    image: zilliz/attu:v2.5.6
    environment:
      MILVUS_URL: milvus-standalone-word:19530
      MILVUS_USERNAME: ${MILVUS_USERNAME}
      MILVUS_PASSWORD: ${MILVUS_PASSWORD}
    ports:
      - "8802:3000"   # UI Attu
    depends_on:
      - milvus-standalone-word

  docling-api-word:
    container_name: docling-api-word
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "18000:8000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8000"
      UPLOAD_DIR: "/app/uploads"
      MILVUS_DB_HOST: "http://milvus-standalone-word"
      MILVUS_DB_PORT: "19530"
    depends_on:
      - milvus-standalone-word

volumes:
  etcd_data_word:
  minio_data_word:
  milvus_data_word:
